export type RootStackParamList = {
  SplashScreen: undefined;
  OnboardScreen: undefined;
  SignupScreen: undefined;
  AuthenticationScreen: undefined;
  EmailLoginScreen: undefined;
  PhoneLoginScreen: undefined;
  ResetPasswordScreen: undefined;
  OTPScreen: undefined;
  HomeShowScreen: undefined;
  HomeScreen: undefined;
  SearchInputScreen: undefined;
  SearchResultScreen: undefined;
  BookingDetailsScreen: undefined;
  CardPaymentScreen: undefined;
  BoardingPassScreen: undefined;
  BookingUserInfoScreen: undefined;
  SelectSeatScreen: undefined;
  FlightSmartSearchResultScreen: undefined;
  FlightPassengerInfoScreen: undefined;
};
